### ISSUE TITLE
ワークスペース作成画面の入力項目の整理および文言を修正

### ISSUE THREAD

**Issue by shiota-2021** [exastro-suite/epoch#10]
使い勝手向上のため項目を精査し、以下の内容を修正します
- アプリケーションコードリポジトリ モーダル画面のGitアカウントパスワードを削除し、トークンのみで動作させる
- TEKTON モーダル画面のコンテキストパスを削除
- IaCリポジトリ モーダル画面のGitアカウントパスワードを削除し、トークンのみで動作させる
- 各モーダル画面の文言変更・placeholderの文言見直し

**Comment by Eiji-Nakahashi** [comment]
すべて完了
