### ISSUE TITLE
ワークスペース作成画面の最新化

### ISSUE THREAD

**Issue by matsumoto-epoch** [exastro-suite/epoch#22]
UI画面について以下を修正
- Manifestパラメータモーダルに項目説明欄を追加
- Manifestパラメータモーダルのタブの並び順を昇順にソート化
- CD実行指定モーダルの「Kubernetes API Server URL」に、EPOCHと同じデプロイ先の場合デフォルトのURLが表示されるように修正
- ArgoCDモーダルの環境名を入力⇒削除した際に、環境タブに削除後の値が反映されないバグを修正

**Comment by y-oka2** [comment]
上記修正が完了したためクローズ
