### ISSUE TITLE
EPOCHをEKSにインストールして動作させたい

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/epoch#224]

**Comment by KaNakayama** [comment]
## 背景
- 開発チームが、ドキュメントチームが作ったEKSの導入手順をなぞり、EPOCHがどのように動かせるか試せていない

## 価値
- EPOCHをEKSで動作せられるようになり、ECRなどとの連携がどのようにできるか試せる環境ができる
- ユーザーからEKSのEPOCHについて問い合わせが来た際、開発チームとして対応ができるようになる

## 受入基準
- EKSクラスタが構築されていること
- EKSクラスタにEPOCHをインストールし、CI/CDが行えること
- はまったところはメモや手順を残してあること

## 開発Tが試したい、確認したい事項
- そのままで動かない部分は外して動くように多少手を入れてでも動かす

## やらないこと
- 永続化 PV部分
