### ISSUE TITLE
バグ修正

### ISSUE THREAD

**Issue by shiota-2021** [exastro-suite/epoch#58]
・アプリケーションコードリポジトリを削除できない事象を改善
・デプロイ先の環境を削除できない事象を改善
・ワークスペース更新時に既にデプロイしたリソースが消える事象を改善

**Comment by shiota-2021** [comment]
・ワークスペースの実行中のボタンクリック時のJavascriptエラー発生の改善
・デプロイのsync/rollbackの権限チェックの対処を追加

**Comment by Eiji-Nakahashi** [comment]
- ワークスペース更新時にmanifestパラメータ設定漏れの修正

**Comment by Eiji-Nakahashi** [comment]
Closed with version 1.0.0 release
