### ISSUE TITLE
GUIの修正

### ISSUE THREAD

**Issue by shiota-2021** [exastro-suite/epoch#63]
- helpボタンからコミュニティーサイトを起動できるように修正
- ワークスペース一覧の行選択でワークスペース画面に遷移するように修正

**Comment by Eiji-Nakahashi** [comment]
- 認証基盤における日本語化対応（初期設定による）

**Comment by Eiji-Nakahashi** [comment]
- ワークスペース一覧からワークスペースの選択方式変更
- お気に入りiconの追加
-

**Comment by Eiji-Nakahashi** [comment]
Closed with version 1.0.0 release
